# Clean GPW Share
# Delete Intermediate files generated by grid_preprocess
# List of Intermediate Files

# Kytt MacManus
# January 5, 2014

# Import Libraries
import arcpy, os
import datetime
startTime = datetime.datetime.now()
# Define Workspace Variable
workspace = r'\\Dataserver0\gpw\GPW4\Gridding\country\rasters'

# Assign workspace environment for ArcPy
arcpy.env.workspace = workspace

# List GDBs in workspace environment
gdbs = arcpy.ListWorkspaces("ar*","FILEGDB")
gdbs.sort()
# Iterate the list
for gdb in gdbs:
    if gdb[-7:-4]=="abw":
        pass
    elif gdb[-7:-4]=="afg":
        pass
    elif gdb[-7:-4]=="ago":
        pass
    elif gdb[-7:-4]=="aia":
        pass
    
    else:
        # get ISO code for name parsing
        iso = os.path.basename(gdb)[:-10]
        print "processing " + iso
        # Assign workspace environment for ArcPy
        # So that we can use shorthand to refer to
        # files located in that database
        arcpy.env.workspace = gdb
        ## Create List of Delete Fields
        meanArea = iso + "_MEAN_ADMIN_UNIT_AREA"
        numInputs = iso + "_NUMINPUTS"
        # define the list
        deleteList = [numInputs,meanArea]
        # iterate delete list
        for deleteFile in deleteList:
            # if the file exists then delete it, otherwise pass
            if arcpy.Exists(deleteFile):
                try:
                    arcpy.Delete_management(deleteFile)
                    print "Deleted " + deleteFile
                except:
                    print arcpy.GetMessages()
            else:
                pass
    

print datetime.datetime.now() - startTime
